version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: predict_api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn predict:app --host 0.0.0.0 --port 8000

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: drift_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run dashboard.py --server.port 8501
